
package base_de_données;

import Application.BDD;
import Application.Parameter;
import Application.ResultSetTableModel;
import java.sql.Date;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import java.lang.*;
import java.awt.Graphics;
import java.awt.Color;

public class Paiement extends javax.swing.JFrame {

    ResultSet rs ;
    BDD db;
    /**
     * Creates new form Paiement
     */
    public Paiement() {
         db = new BDD(new Parameter().HOST_DB, new Parameter().USERNAME_DB,new Parameter()
             .PASSWORD_DB, new Parameter().IPHOST, new Parameter().PORT); 
        initComponents();
        table();
    }
    
     public void table() {
        String a[] = {"num_f", "nom", "prenom", "date","montant","avance","reste"};
        rs = db.querySelect(a, "facture");
        table_f.setModel(new ResultSetTableModel(rs));
    }
     void actualiser() {
       Calendar c = Calendar.getInstance();
       java.util.Date date = c.getTime();
        txt_nomf.setText("");
        txt_prenomf.setText("");
        txt_datef.setDate(date);
        txt_montant.setText("");
        txt_avance.setText("");
        txt_reste.setText("");

     }
     public void reste(){
        int m = Integer.parseInt(txt_montant.getText());
        int a = Integer.parseInt(txt_avance.getText());
        int r = m-a;
        txt_reste.setText(Integer.toString(r));
     }
     
     public void importer() {
        String num_f = String.valueOf(table_f.getValueAt(table_f.getSelectedRow(), 0));
        String colon[] = {"num_f","nom","prenom","montant","avance","reste"};
        rs = db.fcSelectCommand(colon, "facture", "num_f='" + num_f + "'");
        table_f.setModel(new ResultSetTableModel(rs));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table_f = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_reste = new javax.swing.JTextField();
        txt_rechf = new javax.swing.JTextField();
        txt_prenomf = new javax.swing.JTextField();
        txt_montant = new javax.swing.JTextField();
        txt_avance = new javax.swing.JTextField();
        txt_datef = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        txt_nomf = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        com_rechf = new javax.swing.JComboBox<>();
        jButton7 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(870, 800));
        getContentPane().setLayout(null);

        table_f.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "num_f", "nom", "prenom", "date", "montant", "avance", "reste"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table_f.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_fMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_f);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(70, 70, 670, 150);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(142, 198, 212));
        jLabel1.setText("Gestion des paiements :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(310, 20, 260, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("Reste :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 530, 60, 30);

        jLabel3.setText("Nom :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(140, 340, 50, 14);

        jLabel4.setText("Prénom :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(140, 380, 60, 14);

        jLabel5.setText("Date :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(140, 420, 70, 14);

        jLabel6.setText("Montant :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(140, 460, 70, 14);

        jLabel7.setText("Avance :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(140, 500, 70, 14);

        txt_reste.setSelectedTextColor(new java.awt.Color(255, 0, 0));
        txt_reste.setSelectionColor(new java.awt.Color(255, 153, 153));
        txt_reste.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_resteKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_resteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_resteKeyTyped(evt);
            }
        });
        getContentPane().add(txt_reste);
        txt_reste.setBounds(220, 530, 170, 30);
        getContentPane().add(txt_rechf);
        txt_rechf.setBounds(610, 430, 110, 30);
        getContentPane().add(txt_prenomf);
        txt_prenomf.setBounds(220, 370, 170, 30);

        txt_montant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_montantActionPerformed(evt);
            }
        });
        getContentPane().add(txt_montant);
        txt_montant.setBounds(220, 450, 170, 30);

        txt_avance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_avanceActionPerformed(evt);
            }
        });
        getContentPane().add(txt_avance);
        txt_avance.setBounds(220, 490, 170, 30);

        txt_datef.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(txt_datef);
        txt_datef.setBounds(220, 410, 170, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Générer facture");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(450, 590, 170, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Ajouter ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(230, 290, 100, 30);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Modifier");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(330, 290, 100, 30);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Supprimer");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(430, 290, 110, 30);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("Actualiser");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(540, 290, 120, 30);
        getContentPane().add(txt_nomf);
        txt_nomf.setBounds(220, 330, 170, 30);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("Rechercher");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(490, 430, 120, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Recherche par catégorier");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(520, 370, 210, 17);

        com_rechf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "num_f", "nom", "prenom", "date", "montant", "avance", "reste" }));
        getContentPane().add(com_rechf);
        com_rechf.setBounds(520, 390, 180, 30);

        jButton7.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton7.setText("Page principale");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(240, 590, 160, 30);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(-10, -10, 980, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        actualiser();
        table();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String num_f = String.valueOf(table_f.getValueAt(table_f.getSelectedRow(), 0));
        if (JOptionPane.showConfirmDialog(this, "Êtes-vous sûr de vouloir supprimer ?","Faites attention !", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            db.queryDelete("facture", "num_f=" + num_f);
        } else {
            return;
        }
        table();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String theDate = dateFormat.format(txt_datef.getDate());
        if( txt_nomf.getText().equals("")|| txt_prenomf.getText().equals("")
                || theDate.equals("") || txt_montant.getText().equals("")
                || txt_avance.getText().equals("") 
                ){
        JOptionPane.showMessageDialog(this, "Veuillez remplir les champs importants");
        }
        else{
       int r = Integer.parseInt(txt_montant.getText()) - Integer.parseInt(txt_avance.getText()) ;

        String[] colon = {"nom", "prenom", "date", "montant","avance","reste"};
        String[] inf = {txt_nomf.getText(), txt_prenomf.getText(),
                theDate,txt_montant.getText(),txt_avance.getText(),txt_reste.getText()};
        String num_f = String.valueOf(table_f.getValueAt(table_f.getSelectedRow(), 0));
                System.out.println(db.queryInsert("facture", colon, inf));
                table();
                actualiser();
        
    }      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String theDate = dateFormat.format(txt_datef.getDate());
        if( txt_nomf.getText().equals("")|| txt_prenomf.getText().equals("")
                || theDate.equals("") 
                || txt_montant.getText().equals("")
                || txt_avance.getText().equals("")
                || txt_reste.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Veuillez remplir les champs importants");
        }
        else{
        String[] colon = {"nom", "prenom", "date", "montant","avance","reste"};
        String[] inf = {txt_nomf.getText(), txt_prenomf.getText(),
                theDate,txt_montant.getText(),txt_avance.getText(),txt_reste.getText()};
        String num_f = String.valueOf(table_f.getValueAt(table_f.getSelectedRow(), 0));
                System.out.println(db.queryUpdate("facture", colon, inf, "num_f='" + num_f +"'"));
                table();
                actualiser();
        
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
         if (txt_rechf.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Remplissez le champ de recherche");
        } else {
            if (com_rechf.getSelectedItem().equals("num_f")) {
                rs = db.querySelectAll("facture", "num_f LIKE '%" + txt_rechf.getText() + "%' ");
                table_f.setModel(new ResultSetTableModel(rs));
            } else if (com_rechf.getSelectedItem().equals("nom")) {
                rs = db.querySelectAll("facture", "nom LIKE '%" + txt_rechf.getText() + "%' ");
                table_f.setModel(new ResultSetTableModel(rs));
            } else if (com_rechf.getSelectedItem().equals("prenom")) {
                rs = db.querySelectAll("facture", "prenom LIKE '%" + txt_rechf.getText() + "%' ");
                table_f.setModel(new ResultSetTableModel(rs));
            } 
            else if (com_rechf.getSelectedItem().equals("date")) {
                rs = db.querySelectAll("facture", "date LIKE '%" + txt_rechf.getText() + "%' ");
                table_f.setModel(new ResultSetTableModel(rs));
            } 
            else if (com_rechf.getSelectedItem().equals("montant")) {
                rs = db.querySelectAll("facture", "montant LIKE '%" + txt_rechf.getText() + "%' ");
                table_f.setModel(new ResultSetTableModel(rs));
            } 
             else if (com_rechf.getSelectedItem().equals("avance")) {
                rs = db.querySelectAll("facture", "avance LIKE '%" + txt_rechf.getText() + "%' ");
                table_f.setModel(new ResultSetTableModel(rs));
            }  else if (com_rechf.getSelectedItem().equals("reste")) {
                rs = db.querySelectAll("facture", "reste LIKE '%" + txt_rechf.getText() + "%' ");
                table_f.setModel(new ResultSetTableModel(rs));
            } 
            
        } 
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txt_montantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_montantActionPerformed
        // TODO add your handling code here:
        int m = Integer.parseInt(txt_montant.getText());
    }//GEN-LAST:event_txt_montantActionPerformed

    private void txt_avanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_avanceActionPerformed
        // TODO add your handling code here:
        int a = Integer.parseInt(txt_avance.getText());

    }//GEN-LAST:event_txt_avanceActionPerformed

    private void table_fMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_fMouseClicked
        // TODO add your handling code here:
        txt_nomf.setText(String.valueOf(table_f.getValueAt(table_f.getSelectedRow(), 1)));
        txt_prenomf.setText(String.valueOf(table_f.getValueAt(table_f.getSelectedRow(), 2)));
        txt_datef.setDate(Date.valueOf(table_f.getValueAt(table_f.getSelectedRow(), 3).toString()));
        txt_montant.setText(String.valueOf(table_f.getValueAt(table_f.getSelectedRow(), 4)));
        txt_avance.setText(String.valueOf(table_f.getValueAt(table_f.getSelectedRow(), 5)));
        txt_reste.setText(String.valueOf(table_f.getValueAt(table_f.getSelectedRow(), 6)));

    }//GEN-LAST:event_table_fMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Facture f = new Facture();
        f.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_resteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_resteKeyReleased
        // TODO add your handling code here:
        reste();
    }//GEN-LAST:event_txt_resteKeyReleased

    private void txt_resteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_resteKeyPressed
        // TODO add your handling code here:
        reste();
    }//GEN-LAST:event_txt_resteKeyPressed

    private void txt_resteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_resteKeyTyped
        // TODO add your handling code here:
        reste();
    }//GEN-LAST:event_txt_resteKeyTyped

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        Principale a=new Principale();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Paiement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Paiement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Paiement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Paiement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Paiement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> com_rechf;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_f;
    private javax.swing.JTextField txt_avance;
    private com.toedter.calendar.JDateChooser txt_datef;
    private javax.swing.JTextField txt_montant;
    private javax.swing.JTextField txt_nomf;
    private javax.swing.JTextField txt_prenomf;
    private javax.swing.JTextField txt_rechf;
    private javax.swing.JTextField txt_reste;
    // End of variables declaration//GEN-END:variables
}
