
package base_de_données;


import Application.BDD;
import Application.Parameter;
import Application.ResultSetTableModel;
import com.toedter.calendar.JDateChooser;
import java.sql.Date;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.JTextField;


public class Patient extends javax.swing.JFrame {

    ResultSet rs ;
    BDD db;
    
    public Patient() {
        db = new BDD(new Parameter().HOST_DB, new Parameter().USERNAME_DB,new Parameter()
             .PASSWORD_DB, new Parameter().IPHOST, new Parameter().PORT);    
        initComponents();
        table();
    }
    
    public void table() {
        String a[] = {"id", "nom", "prenom", "age", "adresse","sexe","date_naissance",
        "email","profession","tel","cin","d_iris"};
        rs = db.querySelect(a, "patient");
        table_patient.setModel(new ResultSetTableModel(rs));
    }
     void actualiser() {
      Calendar c = Calendar.getInstance();
      java.util.Date date = c.getTime();
        txt_nom.setText("");
        txt_prenom.setText("");
        txt_age.setText("");
        txt_adresse.setText("");
        com_sexe.setSelectedItem("sexe");
        txt_naiss.setDate(date);
        txt_tel.setText("");
        txt_email.setText("");
        txt_profession.setText("");
        txt_cin.setText("");
        txt_diris.setText("");
        
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_patient = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_nom = new javax.swing.JTextField();
        txt_prenom = new javax.swing.JTextField();
        txt_age = new javax.swing.JTextField();
        txt_adresse = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_profession = new javax.swing.JTextField();
        txt_tel = new javax.swing.JTextField();
        txt_cin = new javax.swing.JTextField();
        txt_diris = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        com_rech = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        txt_rech = new javax.swing.JTextField();
        com_sexe = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButton9 = new javax.swing.JButton();
        txt_naiss = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(870, 570));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(142, 198, 212));
        jLabel1.setText("Gestion des patients : ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(270, 0, 212, 22);

        table_patient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nom", "Prénom", "Âge", "Adresse", "Sexe", "Date_naissance", "Téléphone", "Email", "Profession", "CIN ", "D_iris"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_patient.setGridColor(new java.awt.Color(204, 204, 255));
        table_patient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_patientMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_patient);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 310, 860, 110);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Supprimer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(340, 30, 120, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Actualiser");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(460, 30, 110, 30);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Modifier");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(250, 30, 90, 30);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Ajouter");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(160, 30, 90, 30);

        jLabel4.setText("*Nom : ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 80, 90, 14);

        jLabel5.setText("*Prénom :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 120, 90, 14);

        jLabel6.setText("*Âge :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 160, 90, 14);

        jLabel7.setText("*Adresse :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 200, 90, 14);

        jLabel8.setText("*Sexe :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 240, 90, 14);

        jLabel9.setText("*Date de naissance :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 280, 90, 14);

        jLabel10.setText("Email :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(310, 160, 110, 14);

        jLabel2.setText("*Téléphone :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(300, 80, 110, 14);

        jLabel11.setText("CIN :");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(310, 200, 110, 14);

        jLabel12.setText("*Diamètre d'iris :");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(310, 240, 110, 14);

        jLabel14.setText("Profession :");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(310, 120, 110, 14);
        getContentPane().add(txt_nom);
        txt_nom.setBounds(130, 70, 150, 30);
        getContentPane().add(txt_prenom);
        txt_prenom.setBounds(130, 110, 150, 30);
        getContentPane().add(txt_age);
        txt_age.setBounds(130, 150, 150, 30);
        getContentPane().add(txt_adresse);
        txt_adresse.setBounds(130, 190, 150, 30);

        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });
        getContentPane().add(txt_email);
        txt_email.setBounds(410, 150, 210, 30);
        getContentPane().add(txt_profession);
        txt_profession.setBounds(410, 110, 210, 30);
        getContentPane().add(txt_tel);
        txt_tel.setBounds(410, 70, 210, 30);
        getContentPane().add(txt_cin);
        txt_cin.setBounds(410, 190, 210, 30);
        getContentPane().add(txt_diris);
        txt_diris.setBounds(410, 230, 210, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Recherche par catégorie : ");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(640, 70, 190, 17);

        com_rech.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Id", "Nom", "Prénom", "Âge", "Adresse", "Sexe", "Date_naissance", "Email", "Profession", "Téléphone", "CIN", "D_iris" }));
        com_rech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                com_rechActionPerformed(evt);
            }
        });
        getContentPane().add(com_rech);
        com_rech.setBounds(640, 90, 180, 20);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("Rechercher");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(640, 140, 180, 30);
        getContentPane().add(txt_rech);
        txt_rech.setBounds(640, 110, 180, 30);

        com_sexe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Femme ", "Homme", " " }));
        getContentPane().add(com_sexe);
        com_sexe.setBounds(130, 230, 150, 30);

        jButton6.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton6.setText("Dossier médical");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(20, 470, 160, 25);

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setText("Rendez-vous");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(200, 470, 160, 25);

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setText("Page principale");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(560, 470, 160, 23);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(100, 430, 530, 40);

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton9.setText("Paiement");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(380, 470, 160, 23);

        txt_naiss.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(txt_naiss);
        txt_naiss.setBounds(130, 270, 150, 30);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(-60, -40, 1060, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String id = String.valueOf(table_patient.getValueAt(table_patient.getSelectedRow(), 0));
        if (JOptionPane.showConfirmDialog(this, "Êtes-vous sûr de vouloir supprimer ?","Faites attention !", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            db.queryDelete("patient", "id=" + id);
        } else {
            return;
        }
        table();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        actualiser();
        table();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String theDate = dateFormat.format(txt_naiss.getDate());
         if( txt_nom.getText().equals("")|| txt_prenom.getText().equals("")
                || txt_age.getText().equals("") || txt_adresse.getText().equals("")
                || com_sexe.getSelectedItem().toString().equals("")|| theDate.equals("")
                || txt_tel.getText().equals("")||txt_diris.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Veuillez remplir les champs importants");
        }
        else{
        String[] colon = {"nom", "prenom", "age", "adresse","sexe","date_naissance","tel",
        "email","profession","cin","d_iris"};
        String[] inf = {txt_nom.getText(), txt_prenom.getText(),
                txt_age.getText(),txt_adresse.getText(), com_sexe.getSelectedItem().toString(),
                theDate.toString(),txt_tel.getText(),txt_email.getText(),
                txt_profession.getText(),txt_cin.getText(),txt_diris.getText()};
        String id = String.valueOf(table_patient.getValueAt(table_patient.getSelectedRow(), 0));
                System.out.println(db.queryUpdate("patient", colon, inf, "id='" + id +"'"));
                table();
                actualiser();
        
    }//GEN-LAST:event_jButton3ActionPerformed
    }
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String theDate = dateFormat.format(txt_naiss.getDate());
        if(  txt_nom.getText().equals("")|| txt_prenom.getText().equals("")
                || txt_age.getText().equals("") || txt_adresse.getText().equals("")
                || com_sexe.getSelectedItem().toString().equals("")|| theDate.equals("")
                || txt_tel.getText().equals("")|| txt_diris.getText().equals("") ){
        JOptionPane.showMessageDialog(this, "Veuillez remplir les champs importants");
        }
        else{
        String[] colon = { "nom", "prenom", "age", "adresse","sexe","date_naissance","tel",
        "email","profession","cin","d_iris"};
        String[] inf = {txt_nom.getText(), txt_prenom.getText(),
                txt_age.getText(),txt_adresse.getText(), com_sexe.getSelectedItem().toString(),
                theDate.toString(),txt_tel.getText(),txt_email.getText(),
                txt_profession.getText(),txt_cin.getText(),txt_diris.getText()};
                System.out.println(db.queryInsert("patient", colon, inf));
                table();
                actualiser();
        }     
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void com_rechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_com_rechActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_com_rechActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         if (txt_rech.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Remplissez le champ de recherche");
        } else {
            if (com_rech.getSelectedItem().equals("Id")) {
                rs = db.querySelectAll("patient", "id LIKE '%" + txt_rech.getText() + "%' ");
                table_patient.setModel(new ResultSetTableModel(rs));
            } else if (com_rech.getSelectedItem().equals("Nom")) {
                rs = db.querySelectAll("patient", "nom LIKE '%" + txt_rech.getText() + "%' ");
                table_patient.setModel(new ResultSetTableModel(rs));
            } else if (com_rech.getSelectedItem().equals("Prénom")) {
                rs = db.querySelectAll("patient", "prenom LIKE '%" + txt_rech.getText() + "%' ");
                table_patient.setModel(new ResultSetTableModel(rs));
            } else if (com_rech.getSelectedItem().equals("Âge")) {
                rs = db.querySelectAll("patient", "age LIKE '%" + txt_rech.getText() + "%' ");
                table_patient.setModel(new ResultSetTableModel(rs));
            }else if (com_rech.getSelectedItem().equals("Adresse")) {
                rs = db.querySelectAll("patient", "adresse LIKE '%" + txt_rech.getText() + "%' ");
                table_patient.setModel(new ResultSetTableModel(rs));
            }else if (com_rech.getSelectedItem().equals("Sexe")) {
                rs = db.querySelectAll("patient", "sexe LIKE '%" + txt_rech.getText() + "%' ");
                table_patient.setModel(new ResultSetTableModel(rs));
            }else if (com_rech.getSelectedItem().equals("Date_naissance")) {
                rs = db.querySelectAll("patient", "date_naissance LIKE '%" + txt_rech.getText() + "%' ");
                table_patient.setModel(new ResultSetTableModel(rs));
            }else if (com_rech.getSelectedItem().equals("Email")) {
                rs = db.querySelectAll("patient", "email LIKE '%" + txt_rech.getText() + "%' ");
                table_patient.setModel(new ResultSetTableModel(rs));
            }else if (com_rech.getSelectedItem().equals("Profession")) {
                rs = db.querySelectAll("patient", "profession LIKE '%" + txt_rech.getText() + "%' ");
                table_patient.setModel(new ResultSetTableModel(rs));
            }else if (com_rech.getSelectedItem().equals("Téléphone")) {
                rs = db.querySelectAll("patient", "tel LIKE '%" + txt_rech.getText() + "%' ");
                table_patient.setModel(new ResultSetTableModel(rs));
            }else if (com_rech.getSelectedItem().equals("CIN")) {
                rs = db.querySelectAll("patient", "cin LIKE '%" + txt_rech.getText() + "%' ");
                table_patient.setModel(new ResultSetTableModel(rs));
            }else if (com_rech.getSelectedItem().equals("D_iris")) {
                rs = db.querySelectAll("patient", "d_iris LIKE '%" + txt_rech.getText() + "%' ");
                table_patient.setModel(new ResultSetTableModel(rs));
            }
            
        } 
      
    }//GEN-LAST:event_jButton5ActionPerformed

    private void table_patientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_patientMouseClicked
        // TODO add your handling code here:
        
        
        txt_nom.setText(String.valueOf(table_patient.getValueAt(table_patient.getSelectedRow(), 1)));
        txt_prenom.setText(String.valueOf(table_patient.getValueAt(table_patient.getSelectedRow(), 2)));
        txt_age.setText(String.valueOf(table_patient.getValueAt(table_patient.getSelectedRow(), 3)));
        txt_adresse.setText(String.valueOf(table_patient.getValueAt(table_patient.getSelectedRow(), 4)));
        com_sexe.setSelectedItem(String.valueOf(table_patient.getValueAt(table_patient.getSelectedRow(), 5)));
        txt_naiss.setDate(Date.valueOf(table_patient.getValueAt(table_patient.getSelectedRow(), 6).toString()));
        txt_email.setText(String.valueOf(table_patient.getValueAt(table_patient.getSelectedRow(), 7)));
        txt_profession.setText(String.valueOf(table_patient.getValueAt(table_patient.getSelectedRow(), 8)));
        txt_tel.setText(String.valueOf(table_patient.getValueAt(table_patient.getSelectedRow(), 9)));
        txt_cin.setText(String.valueOf(table_patient.getValueAt(table_patient.getSelectedRow(), 10)));
        txt_diris.setText(String.valueOf(table_patient.getValueAt(table_patient.getSelectedRow(), 11)));
    }//GEN-LAST:event_table_patientMouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
         Principale a=new Principale();
         a.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
         Visite a=new Visite();
         a.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        Paiement a=new Paiement();
         a.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
         Dossiermédical a=new Dossiermédical();
         a.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Patient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> com_rech;
    private javax.swing.JComboBox<String> com_sexe;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable table_patient;
    private javax.swing.JTextField txt_adresse;
    private javax.swing.JTextField txt_age;
    private javax.swing.JTextField txt_cin;
    private javax.swing.JTextField txt_diris;
    private javax.swing.JTextField txt_email;
    private com.toedter.calendar.JDateChooser txt_naiss;
    private javax.swing.JTextField txt_nom;
    private javax.swing.JTextField txt_prenom;
    private javax.swing.JTextField txt_profession;
    private javax.swing.JTextField txt_rech;
    private javax.swing.JTextField txt_tel;
    // End of variables declaration//GEN-END:variables
}
