package base_de_données;

import Application.BDD;
import Application.Parameter;
import Application.ResultSetTableModel;
import java.sql.Date;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;

public class Visite extends javax.swing.JFrame {

     ResultSet rs ;
     BDD db;
    
    public Visite() {
        db = new BDD(new Parameter().HOST_DB, new Parameter().USERNAME_DB,new Parameter()
             .PASSWORD_DB, new Parameter().IPHOST, new Parameter().PORT); 
        initComponents();
        table();
    }

     public void table() {
        String a[] = {"num_rdv", "nom", "prenom", "date","heure"};
        rs = db.querySelect(a, "rdv");
        table_rdv.setModel(new ResultSetTableModel(rs));
    }
     void actualiser() {
       Calendar c = Calendar.getInstance();
       java.util.Date date = c.getTime();
        txt_nomrdv.setText("");
        txt_prenomrdv.setText("");
        txt_date.setDate(date);
        txt_heure.setText("");
        
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_rdv = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_heure = new javax.swing.JTextField();
        txt_nomrdv = new javax.swing.JTextField();
        txt_prenomrdv = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        com_rechrdv = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        txt_rechrdv = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        txt_date = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(870, 570));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(142, 198, 212));
        jLabel1.setText("Gestion des rendez-vous :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 20, 260, 22);

        table_rdv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "num_rdv", "nom", "prenom", "date", "heure "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table_rdv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_rdvMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_rdv);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(80, 270, 540, 110);

        jLabel2.setText("Heure :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 240, 70, 14);

        jLabel3.setText("Nom :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 120, 70, 14);

        jLabel4.setText("Prénom : ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 160, 70, 14);

        jLabel5.setText("Date :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(90, 200, 50, 14);
        getContentPane().add(txt_heure);
        txt_heure.setBounds(180, 230, 120, 30);
        getContentPane().add(txt_nomrdv);
        txt_nomrdv.setBounds(180, 110, 120, 30);
        getContentPane().add(txt_prenomrdv);
        txt_prenomrdv.setBounds(180, 150, 120, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Actualiser");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(410, 60, 110, 25);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Rechercher");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(340, 210, 150, 30);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Modifier");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(190, 60, 100, 25);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Recherche par catégorie :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(340, 130, 270, 17);

        com_rechrdv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "num_rdv", "nom", "prenom", "date", "heure", " " }));
        getContentPane().add(com_rechrdv);
        com_rechrdv.setBounds(340, 160, 250, 30);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("Ajouter ");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(90, 60, 100, 25);
        getContentPane().add(txt_rechrdv);
        txt_rechrdv.setBounds(490, 210, 100, 30);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("Supprimer");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(290, 60, 120, 25);

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setText("Retour");
        jButton7.setPreferredSize(new java.awt.Dimension(870, 570));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(250, 390, 150, 30);

        txt_date.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(txt_date);
        txt_date.setBounds(180, 190, 120, 30);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(-10, -10, 970, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        actualiser();
        table();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String theDate = dateFormat.format(txt_date.getDate());
        if( txt_nomrdv.getText().equals("")|| txt_prenomrdv.getText().equals("")
                || theDate.equals("") || txt_heure.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Veuillez remplir les champs importants");
        }
        else{
        String[] colon = {"nom", "prenom", "date", "heure"};
        String[] inf = {txt_nomrdv.getText(), txt_prenomrdv.getText(),
                theDate,txt_heure.getText()};
        String num_rdv = String.valueOf(table_rdv.getValueAt(table_rdv.getSelectedRow(), 0));
                System.out.println(db.queryUpdate("rdv", colon, inf, "num_rdv='" + num_rdv +"'"));
                table();
                actualiser();
        
    }                                     
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String theDate = dateFormat.format(txt_date.getDate());
        if( txt_nomrdv.getText().equals("")|| txt_prenomrdv.getText().equals("")
                || theDate.equals("") || txt_heure.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Veuillez remplir les champs importants");
        }
        else{
        String[] colon = {"nom", "prenom", "date", "heure"};
        String[] inf = {txt_nomrdv.getText(), txt_prenomrdv.getText(),
                theDate,txt_heure.getText()};
        String num_rdv = String.valueOf(table_rdv.getValueAt(table_rdv.getSelectedRow(), 0));
                System.out.println(db.queryInsert("rdv", colon, inf));
                table();
                actualiser();
        
    }      
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (txt_rechrdv.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Remplissez le champ de recherche");
        } else {
            if (com_rechrdv.getSelectedItem().equals("num_rdv")) {
                rs = db.querySelectAll("rdv", "num_rdv LIKE '%" + txt_rechrdv.getText() + "%' ");
                table_rdv.setModel(new ResultSetTableModel(rs));
            } else if (com_rechrdv.getSelectedItem().equals("nom")) {
                rs = db.querySelectAll("rdv", "nom LIKE '%" + txt_rechrdv.getText() + "%' ");
                table_rdv.setModel(new ResultSetTableModel(rs));
            } else if (com_rechrdv.getSelectedItem().equals("prenom")) {
                rs = db.querySelectAll("rdv", "prenom LIKE '%" + txt_rechrdv.getText() + "%' ");
                table_rdv.setModel(new ResultSetTableModel(rs));
            } 
            else if (com_rechrdv.getSelectedItem().equals("date")) {
                rs = db.querySelectAll("rdv", "date LIKE '%" + txt_rechrdv.getText() + "%' ");
                table_rdv.setModel(new ResultSetTableModel(rs));
            } 
            else if (com_rechrdv.getSelectedItem().equals("heure")) {
                rs = db.querySelectAll("rdv", "heure LIKE '%" + txt_rechrdv.getText() + "%' ");
                table_rdv.setModel(new ResultSetTableModel(rs));
            } 
            
        } 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void table_rdvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_rdvMouseClicked
        // TODO add your handling code here:
        txt_nomrdv.setText(String.valueOf(table_rdv.getValueAt(table_rdv.getSelectedRow(), 1)));
        txt_prenomrdv.setText(String.valueOf(table_rdv.getValueAt(table_rdv.getSelectedRow(), 2)));
        txt_date.setDate(Date.valueOf(table_rdv.getValueAt(table_rdv.getSelectedRow(), 3).toString()));
        txt_heure.setText(String.valueOf(table_rdv.getValueAt(table_rdv.getSelectedRow(), 4)));
 
    }//GEN-LAST:event_table_rdvMouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String num_rdv = String.valueOf(table_rdv.getValueAt(table_rdv.getSelectedRow(), 0));
        if (JOptionPane.showConfirmDialog(this, "Êtes-vous sûr de vouloir supprimer ?","Faites attention !", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            db.queryDelete("rdv", "num_rdv=" + num_rdv);
        } else {
            return;
        }
        table();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        Principale a=new Principale();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Visite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Visite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Visite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Visite().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> com_rechrdv;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_rdv;
    private com.toedter.calendar.JDateChooser txt_date;
    private javax.swing.JTextField txt_heure;
    private javax.swing.JTextField txt_nomrdv;
    private javax.swing.JTextField txt_prenomrdv;
    private javax.swing.JTextField txt_rechrdv;
    // End of variables declaration//GEN-END:variables
}
